# build-deploy.ps1 — quick iteration: compile, package, and install the extension.
param(
  [switch]$NoInstall  # build + package only, skip installing into VS Code
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

Write-Host '== Cleaning out/ ==' -ForegroundColor Cyan
# tsc only adds/overwrites — it never prunes. Without this, the compiled output of
# a deleted module keeps shipping inside the .vsix (that is how a removed feature's
# code survived here before).
if (Test-Path 'out') { Remove-Item -Recurse -Force 'out' }

Write-Host '== Compiling ==' -ForegroundColor Cyan
& npm run compile
if ($LASTEXITCODE -ne 0) { throw 'Compile failed.' }

Write-Host '== Packaging ==' -ForegroundColor Cyan
try {
  & .\node_modules\.bin\vsce package --allow-missing-repository
  if ($LASTEXITCODE -ne 0) { throw 'Package failed.' }
}
finally {
  # The reported-tag l10n catalogs (package.nls.zh-cn.json, l10n/bundle.l10n.zh-cn.json,
  # …) are generated by `vscode:prepublish` and exist only while vsce reads the tree.
  # They are in the .vsix already; this takes them off disk again. See
  # docs/agents/invariants/i18n.md.
  Write-Host '== Cleaning generated l10n aliases ==' -ForegroundColor Cyan
  & node tools\sync-l10n-aliases.js --clean
  if ($LASTEXITCODE -ne 0) {
    Write-Host 'Warning: the generated l10n aliases were left on disk (they are gitignored).' -ForegroundColor Yellow
  }
}

# Collect the package into artifacts/, where every build output lives. `--strict` means a
# run that did not actually produce a package fails here instead of installing yesterday's.
Write-Host '== Collecting artifacts ==' -ForegroundColor Cyan
& node tools\collect-artifacts.mjs --vsix --strict
if ($LASTEXITCODE -ne 0) { throw 'Collecting the packaged extension failed.' }
$version = (Get-Content (Join-Path $root 'package.json') -Raw | ConvertFrom-Json).version
# Installed **by exact path**: the old "newest *.vsix in the repository root" heuristic is
# what let six stale packages pile up there, and it would happily install a file this run
# did not produce.
$vsix = Join-Path $root "artifacts\spinney-$version.vsix"
if (-not (Test-Path $vsix)) { throw "No packaged extension at $vsix." }

if ($NoInstall) {
  Write-Host 'Skipping install (build + package only).' -ForegroundColor Yellow
  Write-Host 'The package is in artifacts/.' -ForegroundColor Yellow
  exit 0
}

$cmd = Get-Command code -ErrorAction SilentlyContinue
$code = if ($cmd) { $cmd.Source } else { 'code' }

Write-Host "== Installing $(Split-Path -Leaf $vsix) ==" -ForegroundColor Cyan
& $code --install-extension $vsix --force
if ($LASTEXITCODE -ne 0) { throw 'Install failed.' }

Write-Host 'Done. Reload the VS Code window to activate the changes.' -ForegroundColor Green
