<Project Sdk="Microsoft.NET.Sdk.Web">

  <Sdk Name="StuDev.AotAnywhere" Version="1.0.5" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>spinney-relay</AssemblyName>
    <RootNamespace>SpinneyRelay</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
