// check-docs.js — fails the build when the **user manual** drifts away from the manifest.
//
// The manual is the shipped, user-facing documentation (`manual/**`), served by the
// `spinney.showManual` command (`src/manual.ts`) as an untitled markdown tab one
// language per page. It is not `docs/agents/**`: that tree is written for an agent,
// `.vscodeignore` keeps it out of the package, and nothing here reads it.
//
// Four things drift, and every one of them fails *packaging* instead of the user:
//
//   1. A page goes missing. The extension ships one page per catalog language
//      (`manual.md` + `manual.<canonical tag>.md`, the tags `l10n/` names), so a
//      language that ships UI strings but no manual falls back to English in
//      silence. The page set is derived from `l10n/bundle.l10n.<tag>.json` — the
//      **canonical** names only, because `sync:l10n` has already written the
//      reported-tag copies by the time this runs (`zh-cn` / `zh-tw` are generated
//      aliases of `zh-Hans` / `zh-Hant`, and `languageTags.ts` is the pair).
//   2. The translations fall out of step. A reworded English section is invisible
//      in a translation that still has the old shape, so the **heading level
//      sequence** must be identical in every page (the words are free, the
//      structure is not).
//   3. A command or a setting disappears from the reference tables. Every
//      `contributes.commands` entry must appear in each page **by its localized
//      title** (the value `package.nls*.json` holds, which is what the palette
//      shows), and every `spinney.*` key of `contributes.configuration` must
//      appear verbatim. A renamed title therefore fails here rather than leaving a
//      manual that names a command the user cannot find.
//   4. The pages never reach the user. `.vscodeignore` exclusions are silent — an
//      ignored folder simply is not in the `.vsix`, and the command throws at
//      runtime. The ignore file is evaluated here the way `vsce` reads it
//      (last match wins, `!` re-includes, a pattern without a slash matches the
//      base name).
//
// Run by `npm run check:docs`, which `vsce package` executes through
// `vscode:prepublish` — after `compile`, because the language pair is read from
// `out/languageTags.js` the way `check-models.js` reads `out/agent/models.js`.
// `node tools/check-docs.js <dir>` checks another manual folder instead, which is
// how to prove this guard still catches what it is for.

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const manualDir = process.argv[2] ? path.resolve(process.argv[2]) : path.join(root, 'manual');
const shippedDirName = path.basename(manualDir);

const tagsPath = path.join(root, 'out', 'languageTags.js');
if (!fs.existsSync(tagsPath)) {
  console.error('check-docs: out/languageTags.js is missing — run `npm run compile` first.');
  process.exit(1);
}
const { REPORTED_TAGS } = require(tagsPath);

const problems = [];

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function read(file) {
  return fs.readFileSync(file, 'utf8');
}

/** The relative path of a page as `.vscodeignore` and vsce see it. */
function relOf(file) {
  return path.relative(root, file).replace(/\\/g, '/');
}

// --- 1. which pages must exist ----------------------------------------------
//
// The language set is the shipped **runtime catalogs**, under their canonical
// names. The reported-tag copies (`zh-cn`, `zh-tw`) are generated by `sync:l10n`
// and are not languages of their own.
const aliasTags = new Set(Object.values(REPORTED_TAGS));
const languages = fs
  .readdirSync(path.join(root, 'l10n'))
  .map((name) => /^bundle\.l10n\.(.+)\.json$/.exec(name))
  .filter((m) => !!m && !aliasTags.has(m[1]))
  .map((m) => m[1])
  .sort();

/** One page per language, English first: `manual.md`, then `manual.<tag>.md`. */
const pages = [{ language: '', file: path.join(manualDir, 'manual.md') }].concat(
  languages.map((tag) => ({ language: tag, file: path.join(manualDir, `manual.${tag}.md`) })),
);

if (languages.length === 0) {
  problems.push('l10n/ holds no bundle.l10n.<tag>.json catalog — the manual has no language set to check');
}

for (const page of pages) {
  if (!fs.existsSync(page.file)) {
    problems.push(
      `${relOf(page.file)} is missing — ${page.language ? `the ${page.language} window` : 'every window that falls back to it'} would get no manual`,
    );
  } else if (read(page.file).trim().length === 0) {
    problems.push(`${relOf(page.file)} is empty`);
  }
}

// --- 2. the pages keep the same shape ---------------------------------------
//
// The words differ per language, the structure does not: one heading level
// sequence per page, identical everywhere.
function headingLevels(text) {
  return text
    .split(/\r?\n/)
    .filter((line) => /^#{1,6}\s+\S/.test(line))
    .map((line) => line.match(/^#+/)[0].length);
}

const present = pages.filter((page) => fs.existsSync(page.file));
const shapes = present.map((page) => ({ page, levels: headingLevels(read(page.file)) }));
if (shapes.length > 0 && shapes[0].levels.length === 0) {
  problems.push(`${relOf(shapes[0].page.file)} has no heading at all — every page must carry the manual's sections`);
}
for (const shape of shapes.slice(1)) {
  const base = shapes[0];
  if (shape.levels.join(',') !== base.levels.join(',')) {
    problems.push(
      `${relOf(shape.page.file)} has ${shape.levels.length} heading(s) against ${base.levels.length} in ${relOf(base.page.file)} — the translated pages must keep the English structure`,
    );
  }
}

// --- 3. the reference tables name what the manifest declares -----------------
const pkg = readJson(path.join(root, 'package.json'));
const englishNls = readJson(path.join(root, 'package.nls.json'));

/** `contributes.configuration` is one entry per Settings-UI group, so flatten it. */
function configurationProperties(contributes) {
  const sections = contributes?.configuration;
  return (Array.isArray(sections) ? sections : sections ? [sections] : []).reduce(
    (all, section) => Object.assign(all, section?.properties ?? {}),
    {},
  );
}

const commandIds = (pkg.contributes?.commands ?? []).map((c) => c.command);
const settingKeys = Object.keys(configurationProperties(pkg.contributes));

for (const { language, file } of present) {
  const rel = relOf(file);
  const text = read(file);
  const nlsPath = path.join(root, language ? `package.nls.${language}.json` : 'package.nls.json');
  if (!fs.existsSync(nlsPath)) {
    problems.push(`${rel}: package.nls${language ? `.${language}` : ''}.json is missing — there is no title to check against`);
    continue;
  }
  const nls = language ? readJson(nlsPath) : englishNls;

  for (const id of commandIds) {
    const title = nls[`command.${id}.title`];
    if (!title) {
      problems.push(`package.nls${language ? `.${language}` : ''}.json has no command.${id}.title`);
      continue;
    }
    if (!text.includes(title)) {
      problems.push(`${rel}: the command reference does not mention "${title}" (${id}) — the palette shows that title`);
    }
  }

  for (const key of settingKeys) {
    if (!text.includes(key)) {
      problems.push(`${rel}: the settings reference does not mention ${key}`);
    }
  }
}

// --- 4. the pages really ship ------------------------------------------------
//
// vsce reads only `.vscodeignore`, and the last matching line wins; `!` puts a
// path back. A pattern without a slash matches the base name at any depth, the
// way gitignore does.
function ignoreMatcher(pattern) {
  let p = pattern.replace(/^\/+/, '').replace(/\/+$/, '');
  if (!p) {
    return null;
  }
  let re = '';
  for (let i = 0; i < p.length; i++) {
    const ch = p[i];
    if (ch === '*') {
      if (p[i + 1] === '*') {
        i++;
        // `**/` spans any number of directories, a bare `**` spans anything.
        if (p[i + 1] === '/') {
          i++;
          re += '(?:.*/)?';
        } else {
          re += '.*';
        }
      } else {
        re += '[^/]*';
      }
    } else if (ch === '?') {
      re += '[^/]';
    } else {
      re += ch.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    }
  }
  // `docs/**` must also cover the folder itself, and a file pattern covers it.
  return new RegExp(`^${re}(?:/.*)?$`);
}

const ignoreFile = path.join(root, '.vscodeignore');
if (fs.existsSync(ignoreFile)) {
  const lines = read(ignoreFile).split(/\r?\n/);
  for (const { language, file } of present) {
    const rel = relOf(file);
    let ignored = false;
    for (const line of lines) {
      const raw = line.trim();
      if (!raw || raw.startsWith('#')) {
        continue;
      }
      const negated = raw.startsWith('!');
      const regex = ignoreMatcher(negated ? raw.slice(1).trim() : raw);
      if (!regex) {
        continue;
      }
      // A pattern with no slash matches the base name at any depth.
      const target = raw.includes('/') ? rel : path.basename(rel);
      if (regex.test(target)) {
        ignored = !negated;
      }
    }
    if (ignored) {
      problems.push(
        `${rel} is excluded by .vscodeignore, so it never reaches the .vsix — the ${language || 'English'} manual would not ship`,
      );
    }
  }
}

// --- the summary --------------------------------------------------------------
if (problems.length) {
  console.error('check-docs: the user manual drifted from the manifest\n');
  for (const p of problems) {
    console.error('  ' + p);
  }
  console.error('\nThe source of truth is manual/manual.md (English); the other pages translate it.');
  process.exit(1);
}

console.log(
  `check-docs: OK — ${pages.length} page(s) in ${shippedDirName}/ (${pages
    .map((page) => path.basename(page.file))
    .join(', ')}), ${commandIds.length} command(s), ${settingKeys.length} setting(s), all shipped.`,
);
